from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from ..models.database import get_db, User
from ..services.project_service import ProjectService
from .deps import get_current_user
import io
import os
from datetime import datetime

# Advanced PDF Generation dependencies
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table, TableStyle, 
    Image, PageBreak, KeepTogether, NextPageTemplate
)
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY

# Matplotlib for charts (if available)
try:
    import matplotlib
    matplotlib.use('Agg') # Fix for threading issues in FastAPI
    import matplotlib.pyplot as plt
    import seaborn as sns
    HAS_CHARTS = True
    plt.style.use('ggplot')
except ImportError:
    HAS_CHARTS = False

router = APIRouter()

# --- BRAND COLORS ---
PRIMARY_HEX = '#0c4a6e'
SECONDARY_HEX = '#0ea5e9'
ACCENT_HEX = '#38bdf8'
SUCCESS_HEX = '#10b981'
DANGER_HEX = '#ef4444'
PRIMARY_COLOR = colors.HexColor(PRIMARY_HEX)
GRAY_LINE = colors.HexColor('#e2e8f0')

class PDFReportGenerator:
    def __init__(self, db: Session, project_id: int):
        self.db = db
        self.project_id = project_id
        self.metrics = ProjectService.get_project_metrics(db, project_id)
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
        
    def _create_custom_styles(self):
        self.styles.add(ParagraphStyle(
            name='CoverTitle', parent=self.styles['Title'], fontSize=36, leading=42, textColor=colors.white,
            alignment=TA_LEFT, spaceAfter=20, fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader', parent=self.styles['Heading2'], fontSize=16, leading=20, textColor=PRIMARY_COLOR,
            spaceBefore=20, spaceAfter=15, fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='NormalJustified', parent=self.styles['Normal'], alignment=TA_JUSTIFY, fontSize=10, leading=15, textColor=colors.HexColor('#444444')
        ))

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        width, height = A4
        canvas.setFillColor(PRIMARY_COLOR)
        canvas.rect(0, height - 15, width, 15, fill=1, stroke=0)
        canvas.setFont('Helvetica-Bold', 12)
        canvas.drawString(40, height - 50, f"{self.metrics['project_name']}")
        canvas.drawRightString(width - 40, height - 50, f"{datetime.now().strftime('%B %d, %Y')}")
        canvas.setStrokeColor(GRAY_LINE)
        canvas.line(40, 50, width - 40, 50)
        canvas.setFont('Helvetica', 8)
        canvas.drawString(40, 35, "Generated by Project Management Tool")
        canvas.drawRightString(width - 40, 35, f"Page {doc.page}")
        canvas.restoreState()

    def _cover_page_bg(self, canvas, doc):
        canvas.saveState()
        width, height = A4
        canvas.setFillColor(PRIMARY_COLOR)
        canvas.rect(0, 0, width, height, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        path = canvas.beginPath()
        path.moveTo(width * 0.35, 0)
        path.lineTo(width, 0)
        path.lineTo(width, height)
        path.lineTo(width * 0.35, height)
        path.close()
        canvas.drawPath(path, fill=1, stroke=0)
        canvas.restoreState()

    def _create_financial_chart(self):
        if not HAS_CHARTS: return None
        plt.figure(figsize=(6, 3))
        cats = ['Budget', 'Spent']
        vals = [self.metrics['total_budget'], self.metrics['spent']]
        plt.bar(cats, vals, color=[PRIMARY_HEX, SECONDARY_HEX])
        plt.title('Financial Overview', fontsize=10)
        buf = io.BytesIO()
        plt.savefig(buf, format='png', dpi=150, bbox_inches='tight', transparent=True)
        plt.close()
        buf.seek(0)
        return buf

    def generate(self):
        buffer = io.BytesIO()
        doc = BaseDocTemplate(buffer, pagesize=A4, leftMargin=0.7*inch, rightMargin=0.7*inch)
        
        cover_frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='cover')
        normal_frame = Frame(doc.leftMargin, doc.bottomMargin + 30, doc.width, doc.height - 80, id='normal')
        
        doc.addPageTemplates([
            PageTemplate(id='cover_page', frames=cover_frame, onPage=self._cover_page_bg),
            PageTemplate(id='report_page', frames=normal_frame, onPage=self._header_footer)
        ])
        
        story = []
        # --- COVER ---
        story.append(Spacer(1, 2*inch))
        cover_data = [[
            Paragraph("PROJECT<br/>STATUS<br/>REPORT", self.styles['CoverTitle']),
            Paragraph(f"<br/><br/><br/><b>{self.metrics['project_name']}</b>", 
                      ParagraphStyle('CR', parent=self.styles['Normal'], fontSize=20, textColor=PRIMARY_COLOR))
        ]]
        story.append(Table(cover_data, colWidths=[3.5*inch, 4*inch]))
        story.append(NextPageTemplate('report_page'))
        story.append(PageBreak())
        
        # --- CONTENT ---
        story.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
        summary_text = ProjectService.get_executive_summary(self.db, self.project_id)
        story.append(Paragraph(summary_text, self.styles['NormalJustified']))
        
        if HAS_CHARTS:
            chart_buf = self._create_financial_chart()
            if chart_buf:
                story.append(Spacer(1, 20))
                story.append(Image(chart_buf, width=5*inch, height=2.5*inch))

        # Metrics Table
        data = [
            ["Metric", "Value"],
            ["Project Number", self.metrics['project_number']],
            ["Budget", f"R {self.metrics['total_budget']:,.2f}"],
            ["Spent", f"R {self.metrics['spent']:,.2f}"],
            ["Physical Completion", f"{self.metrics['percent_complete']}%"],
            ["Schedule Health", self.metrics['schedule_health']]
        ]
        t = Table(data, colWidths=[2.5*inch, 3*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 8)
        ]))
        story.append(Spacer(1, 20))
        story.append(t)
        
        doc.build(story)
        buffer.seek(0)
        return buffer

@router.get("/{project_id}/pdf/")
def get_project_report_pdf(
    project_id: int, 
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    generator = PDFReportGenerator(db, project_id)
    pdf_buffer = generator.generate()
    
    from ..core.audit import log_event
    log_event(
        db,
        event_type="DOWNLOAD",
        category="REPORT",
        description=f"Generated PDF report for project ID {project_id}",
        user_id=current_user.user_id
    )
    
    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename=Report_{project_id}.pdf",
            "Access-Control-Expose-Headers": "Content-Disposition"
        }
    )
